# Generated by Django 5.0.6 on 2024-06-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fooddelivery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurants",
            name="cuisine",
            field=models.CharField(default="Fast Food", max_length=128),
        ),
    ]
