# Generated by Django 5.0.6 on 2024-06-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fooddelivery", "0003_menuitems_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitems",
            name="description",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="restaurants",
            name="image",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
