# Generated by Django 5.0.6 on 2024-06-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fooddelivery", "0004_menuitems_description_restaurants_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurants",
            name="description",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
